In [1]:
import numpy as np

In [61]:
a=np.arange(6)
a2=a[np.newaxis, :]
a2.shape

(1, 6)

In [89]:
b = np.array([1,2,3,4,5,6])
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
#An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element.
a.shape

(3, 4)

In [66]:
print(a[1])
print(b[1])


[5 6 7 8]
2


In [90]:
# The number of dimensions and items in an array is defined by its shape.
#In NumPy, dimensions are called axes. This means that if you have a 2D array that looks like this:
[
    [0., 0., 0.],[1., 1., 2.]
]
#it has 2 axes, first has a length of 2 and second has 3

[[0.0, 0.0, 0.0], [1.0, 1.0, 2.0]]

Creating a basic array

In [87]:
a = np.array([1,2,3])
a.shape
# besides creating an array using a sequence of elements, u can make one filled with 0s.
#np.zeros(2)

(3,)

In [85]:
# or filled with 1's
np.ones(2)

array([1., 1.])

In [83]:
# or empty array
np.empty(2)
#its content is whatevers last stored in the memory.

array([1.02025572e-311, 1.02025572e-311])

In [9]:
#u can create an array with a range of elements.
np.arange(4)

array([0, 1, 2, 3])

In [10]:
#also an array with a range of evenly spaced intervals. specify# first number, last number and the step size.
np.arange(2,9,2)

array([2, 4, 6, 8])

In [11]:
#u can also use np.linspace() to create an array with values which are spaced in a specified interval
np.linspace(0, 10, num=5)
# 0 = starting value,
# 10 = end value,
# num= number of samples to generate. the array has 5 values from 0 to 10 with equal intervals.

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [12]:
x= np.ones(2, dtype=np.int64)
x
#default data type is np.float64, but u can specify which u want to use with dtype keyword argument

array([1, 1], dtype=int64)

Adding, removing and sorting elements.

In [13]:
#sorting an element is simple with np.sort(). u can specify axis, kind and order.
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [91]:
#concatenate arrays.
a = np.array([1, 2, 3, 6])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 6, 5, 6, 7, 8])

In [92]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
#delete an element at index pos 2
arr = np.delete(arr, 2)
arr
#deletes 5

array([2, 1, 3, 7, 4, 6, 8])

How do u know the shape and size of an array?

In [17]:
#array_name.ndim tells u the number of axes, or dimensions
#array_name.size tells u the total number of elements of the array
#array_name.shape displays a taple of integers that indicate the N.o of elements stored along each dimension.

In [18]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [19]:
array_example.ndim

3

In [20]:
array_example.size

24

In [21]:
array_example.shape

(3, 2, 4)

Can u reshape an array

In [22]:
# array_name.reshape gives a new shape to the array with the same data. the new array has to have the same number of elements as the original

In [23]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [24]:
#3 rows 2 columns
b = a.reshape(3,2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [25]:
# u can specify a few optional parameters
np.reshape(a, newshape=(1, 6), order='C')
#a is whats being reshaped
# newshape is the newshape
#order='C' means read/write using C-like index order

array([[0, 1, 2, 3, 4, 5]])

Converting 1D array to 2D ( how to add a new axis)

In [26]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [27]:
#use newaxis to add a new axis
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [28]:
#u can also use a row or column vector using newaxis.
# convert a 1d array to row vector
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [29]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [30]:
# u can also expand an array by inserting a new axis in a specified position with np.expand_dims
a = np.array([1, 2, 3, 4, 5, 6])
b = np.expand_dims(a, axis=1)
#axis at index 1
b.shape

(6, 1)

In [31]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

indexing and slicing.

In [32]:
data = np.array([1,2,3])
data[1]

2

In [33]:
data[0:2]

array([1, 2])

In [34]:
data[1:]

array([2, 3])

In [35]:
data[-2:]

array([2, 3])

Np indexing visualised image.

In [36]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [37]:
#print all values less then 5
print(a[a<5])

[1 2 3 4]


In [38]:
#select numbers equal or great than 5 and index an array.
five_up = (a>=5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [39]:
#elements divisible by 2
divisible_by_2 = a[a%2==0]
divisible_by_2

array([ 2,  4,  6,  8, 10, 12])

In [40]:
c = a[(a>2) & (a<11)]
c

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
five_up = (a > 5) | (a == 5)
five_up
#logical operators to return boolean values if they are true or false

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [42]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [43]:
#u can use np.nonzero() to print indices of elements
b= np.nonzero(a<5)
b

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))

In [44]:
list_of_coordinates = list(zip(b[0], b[1]))
for coord in list_of_coordinates:
    print(coord)
#If you want to generate a list of coordinates where the elements exist, you can zip the arrays, iterate over the list of coordinates, and print them.

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [45]:
#use np.nonzero() to print elements in an array less then 5
print(a[b])

[1 2 3 4]


In [46]:
#if the element ur looking for doesnt exist, empty indices will be returned.
not_there = np.nonzero(a==42)
not_there

(array([], dtype=int64), array([], dtype=int64))

Creating an array from existing data

In [47]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
# u can create a new array from a section of ur array by specifying where to slice
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [49]:
a1 = np.array([[1,1],
              [2,2]])
a2 = np.array([[3,3],
               [4,4]])

In [50]:
# stack vertically with vstack
np.vstack((a1,a2))
# 1 and 2 are stacked above 3 and 4

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [51]:
#np.hstack horizontally stacks the arrays
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [52]:
x = np.arange(1,25).reshape(2,12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [53]:
#horizontally split array into 3 equal arrays
np.hsplit(x,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [54]:
#split your array after the third and fourth column,
np.hsplit(x,(3,4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [55]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [56]:
#create an array b1 by slicing a and modify the first element of b1. This will modify the corresponding element in a as well!
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [57]:
b1[0]=99
b1

array([99,  2,  3,  4])

In [58]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [59]:
# use copy() to make a complete copy of the array and its data
b2 = a.copy()