In [1]:
import numpy as np

Basic array operations

In [2]:
data = np.array([1,2])
ones = np.ones(2, dtype=int)
data+ones

array([2, 3])

In [3]:
data-ones

array([0, 1])

In [4]:
data*data

array([1, 4])

In [5]:
data/data

array([1., 1.])

In [6]:
# to find sum of elements use sum(), works for arrays in all dimensions
a = np.array([1, 2, 3, 4])
a.sum()

np.int64(10)

In [7]:
#to add rows/columns in a 2d array, specify axis
b = np.array([[1, 1], [2, 2]])
b.sum(axis=0)

array([3, 3])

In [8]:
b.sum(axis=1)

array([2, 4])

Broadcasting

In [9]:
data = np.array([1.0, 2.0])
data * 1.6
#

array([1.6, 3.2])

More useful array operations
#mean to get the average, prod to get the result of multiplying the elements together, std to get the standard deviation, and more.

In [10]:
data.max()

np.float64(2.0)

In [11]:
data.min()

np.float64(1.0)

In [12]:
data.sum()

np.float64(3.0)

In [13]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],

              [0.54627315, 0.05093587, 0.40067661, 0.55645993],

              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
a.sum()

np.float64(4.8595784)

In [14]:
a.min()

np.float64(0.05093587)

In [15]:
a.min(axis=0)
# you can find the minimum value within each column by specifying axis=0.

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

Creating Matrices

In [16]:
#you can pass python lists of lists to create a 2d array (matrix) to represent them in numpy

In [17]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
data[0,1] #0 row, 2nd row

np.int64(2)

In [19]:
data[1:3] #1st row to till 3rd

array([[3, 4],
       [5, 6]])

In [20]:
data[0:2, 0] #0 to 2nd row,  0th column

array([1, 3])

In [21]:
data.max()

np.int64(6)

In [22]:
data.min()

np.int64(1)

In [23]:
data.sum()

np.int64(21)

In [24]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data.max(axis=0) #maximum in columns

array([5, 6])

In [25]:
data.max(axis=1) #maximum in rows

array([2, 5, 6])

In [26]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data+ones
# u can add and multiply them using arithmetic operators

array([[2, 3],
       [4, 5]])

In [27]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row #t
#you can use these operators on matrices of different sizes
#if one matrix has one column or one row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [28]:
np.ones((4, 3, 2))
# 4 seperate lists : 3 rows  2 columns

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [29]:
np.ones(3) #3 rows

array([1., 1., 1.])

In [30]:
np.zeros(3)

array([0., 0., 0.])

In [31]:
#simplest way to generate random numbers
rng = np.random.default_rng(0)
rng.random(3)

array([0.63696169, 0.26978671, 0.04097352])

Generating random numbers

In [32]:
rng.integers(5, size=(2, 4))  #random 2x4 array of random int between 0 and 4

array([[0, 0, 0, 4],
       [3, 4, 2, 3]])

How to get unique items and counts
#covers np.unique()

In [33]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [34]:
unique_values = np.unique(a)
print(unique_values) #unique values in array

[11 12 13 14 15 16 17 18 19 20]


In [35]:
unique_values, indices_list = np.unique(a, return_index=True)
#indices of unique values in an array, pass return_index argument in np.unique()
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [36]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)
#pass the return_counts argument in np.unique() along with your array to get the frequency count of unique values

[3 2 2 2 1 1 1 1 1 1]


In [37]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
unique_values = np.unique(a_2d)
print(unique_values)
#also works in 2d arrays
#f the axis argument isn’t passed, your 2D array will be flattened.

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [38]:
#if u want unique rows or columns, pass the axis argument
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)
# axis 0 = rows          axis 1 = columns

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [39]:
#unique rows, index position, and occurrence count
unique_rows, indices, occurrence_count = np.unique(
    a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [40]:
print(indices)

[0 1 2]


In [41]:
print(occurrence_count)

[2 1 1]


Transposing and reshaping a matrix

In [42]:
#arrays have a property T which lets to transpose a matrix
data.reshape(2,3) #2 rows 3 columns
#You simply need to pass in the new dimensions that you want for the matrix.

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

transpose

In [44]:
arr = np.arange(6).reshape((2,3))
#transpose reverses or changes axes
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [45]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [46]:
arr.T #same as transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

Reverse an array

In [47]:
#np.flip() lets to flip or reverse array contents along an axis.
#specify array to be reversed and the axis.

In [48]:
#1d array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reversed_arr = np.flip(arr) #only 1 axis so not needed
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [49]:
#2D arrays
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
reversed_arr = np.flip(arr_2d)
print(reversed_arr)
#reversed rows and columns, both axes

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [50]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)
#reverse only rows

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [51]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)
#reverse only columns

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [52]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)
#reverse the contents of the row at index position 1 (the second row)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [53]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)
#reverse the column at index position 1 (second column)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


Reshaping and flattening multidimensional arrays

In [54]:
#2 ways to flatten an array is flatten() and ravel()
#changes to the new array will affect the parent array in ravel()
# ravel doesnt make a copy its memory efficient

In [55]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [56]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [57]:
a1 = x.flatten()
a1[0]=99
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [58]:
print(a1) #new array

[99  2  3  4  5  6  7  8  9 10 11 12]


In [59]:
a2 = x.ravel()
a2[0] = 98
print(x) #98 is set on the original array aswell

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
